# Generated by Django 4.0.1 on 2022-01-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('metrics', models.JSONField()),
                ('workouts', models.JSONField()),
            ],
        ),
    ]
