# Generated by Django 4.0.1 on 2022-01-21 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HealthData',
            new_name='DayHistory',
        ),
    ]
