# Generated by Django 4.0.1 on 2022-01-21 12:17

import health_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0002_rename_healthdata_dayhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayhistory',
            name='metrics',
            field=models.JSONField(
                default=health_data.models.metric_default, encoder=health_data.models.MetricsEncoder),
        ),
    ]
