# Generated by Django 4.0.1 on 2022-01-21 14:21

from django.db import migrations, models
import health_data.models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0003_alter_dayhistory_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayhistory',
            name='metrics',
            field=models.JSONField(encoder=health_data.models.MetricsEncoder),
        ),
    ]
