# Generated by Django 4.0.1 on 2022-01-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_data', '0004_alter_dayhistory_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayhistory',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
    ]
