# Generated by Django 3.0.5 on 2020-12-20 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ValueChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value_changes', to='plants.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureBorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=100)),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='temperature_borders', to='plants.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='SunlightIntensityBorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=100)),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunlight_intensity_borders', to='plants.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='SoilMoistureBorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=100)),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soil_moisture_borders', to='plants.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='SoilFertitlityBorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=100)),
                ('max', models.IntegerField()),
                ('min', models.IntegerField()),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soil_fertitlity_borders', to='plants.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='PlantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery', models.IntegerField()),
                ('soil_fertility', models.IntegerField()),
                ('soil_moisture', models.IntegerField()),
                ('sunlight', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_data', to='plants.Plant')),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('location_details', models.CharField(max_length=100)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='plants.Plant')),
            ],
        ),
    ]
