# Generated by Django 3.0.5 on 2020-12-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuechanges',
            name='value',
            field=models.CharField(choices=[('F', 'Fertility'), ('M', 'Moisture')], default='F', max_length=2),
            preserve_default=False,
        ),
    ]
