# Generated by Django 3.2.5 on 2021-08-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_valuechanges_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='location_floor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
