# Generated by Django 4.0.1 on 2022-03-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('R', 'Read')], max_length=100),
        ),
    ]
