# Generated by Django 4.0.1 on 2022-03-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_status_notification_notifactionstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notifactionStatus',
            new_name='notificationStatus',
        ),
    ]
